Salsa CI: Unify with similar job logic in MariaDB Server and Entr packages

diff --git a/debian/salsa-ci.yml b/debian/salsa-ci.yml
--- a/debian/salsa-ci.yml
+++ b/debian/salsa-ci.yml
@@ -1,5 +1,5 @@
 ---
-# Include Salsa-CI as a base
+# Include Salsa CI as a base
 include:
   - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/recipes/debian.yml
 
@@ -7,26 +7,26 @@ include:
 variables:
   BUILT_PACKAGES: "galera-4 galera-arbitrator-4"
   SALSA_CI_DISABLE_RC_BUGS: 0
-  # Enable more architectures
-  SALSA_CI_DISABLE_BUILD_PACKAGE_ARMEL: 0
-  SALSA_CI_DISABLE_BUILD_PACKAGE_ARMHF: 0
-  SALSA_CI_DISABLE_BUILD_PACKAGE_ARM64: 0
-  # Enable cross-builds
-  SALSA_CI_DISABLE_CROSSBUILD_ARM64: 0
   # This will always fail as long as tests are superficial:
   #SALSA_CI_AUTOPKGTEST_ALLOWED_EXIT_STATUS: 0
   SALSA_CI_DISABLE_BUILD_PACKAGE_TWICE: 0
   SALSA_CI_ENABLE_ATOMIC_REPROTEST: 0
   SALSA_CI_ENABLE_BUILD_PACKAGE_PROFILES: 1
   BUILD_PROFILES: nocheck,nodoc
+  # Enable more architectures
+  SALSA_CI_DISABLE_BUILD_PACKAGE_ARMEL: 0
+  SALSA_CI_DISABLE_BUILD_PACKAGE_ARMHF: 0
+  SALSA_CI_DISABLE_BUILD_PACKAGE_ARM64: 0
+  # Enable cross-builds
+  SALSA_CI_DISABLE_CROSSBUILD_ARM64: 0
 
 stages:
   - provisioning
   - build
-  - test  # Stage referenced by Salsa-CI template reprotest stanza, so must exist
+  - test  # Stage referenced by Salsa CI template reprotest stanza, so must exist
   - upgrade package
   - upgrade package and distro
-  - publish  # Stage referenced by Salsa-CI template aptly stanza, so must exist even though not used
+  - publish  # Stage referenced by Salsa CI template aptly stanza, so must exist even though not used
 
 gnitpick:
   stage: provisioning
@@ -34,7 +34,7 @@ gnitpick:
   script: |
     # Bare minimal (<4MB) for apt-key and gnitpick to work
     apt-get update -qq && apt-get -qq install --no-install-recommends --yes ca-certificates curl python3-minimal git
-    curl -sS https://raw.githubusercontent.com/Seravo/gnitpick/master/gnitpick.py -o /usr/bin/gnitpick; chmod +x /usr/bin/gnitpick
+    curl -sL https://raw.githubusercontent.com/Seravo/gnitpick/master/gnitpick.py -o /usr/bin/gnitpick; chmod +x /usr/bin/gnitpick
     # Actual Gnitpick part
     gnitpick --target-repository https://salsa.debian.org/mariadb-team/galera-4.git --target-branch debian/latest
   except:
@@ -137,10 +137,11 @@ build bullseye-backports:
 # Define snippets used to construct jobs
 
 .test-prepare-container: &test-prepare-container |
+  # Prepare container for use in CI
   # Change directory to ./debian/output where build artifacts can be found
   cd ${WORKING_DIR}
   # Enable automatic restarts from maint scripts
-  sed -i "s/101/0/g" -i /usr/sbin/policy-rc.d
+  sed -i "s/101/0/g" /usr/sbin/policy-rc.d
   # Fake /sbin/runlevel to avoid warnings of "invoke-rc.d: could not determine current runlevel"
   echo -e '#!/bin/sh\necho "N 5"' > /sbin/runlevel; chmod +x /sbin/runlevel
   # Never stop apt to ask for confirmation, just assume `--yes` all the time
@@ -197,32 +198,32 @@ build bullseye-backports:
   apt-get update -q
 
 .test-enable-sid-repos: &test-enable-sid-repos
-  # Skip this section if already in Sid
+  # If already on Sid, most steps below will be skipped. If upgrading a distro
+  # older than Debian Bookworm, Sid will be enabled only up until March 2025
+  # version as after that a coreutils/util-linux made it impossible to upgrade.
   - |
+    grep PRETTY_NAME /etc/os-release
     if grep -q 'PRETTY_NAME="Debian GNU/Linux trixie/sid"' /etc/os-release
     then
       echo "Already using Sid, no need to enable it"
     else
       # Install tools that may be needed to circumvent issues in the upgrade
       apt-get install -qq --yes --no-install-recommends ca-certificates curl
-      # Replace any old repos with just Sid, and trust blindly as old Debian releases won't have latest Sid in their keyring
+      # Replace any old repos with just Sid
+      rm -vf /etc/apt/sources.list.d/debian.sources
       echo 'deb http://deb.debian.org/debian sid main' > /etc/apt/sources.list
       # Attempting upgrade from Bullseye or older to Debian Sid is no longer
       # possible in April 2025, as even with all usrmerge workarounds applied
-      # the util-linux upgrade is practically impossible due to versioned hard
-      # dependencies:
+      # the coreutils and util-linux upgrade is practically impossible due to
+      # versioned hard dependencies:
       #
       #    coreutils : PreDepends: libsystemd0 (>= 254) but 247.3-7+deb11u6 is to be installed
       #    util-linux : PreDepends: libc6 (>= 2.41) but 2.38-11 is to be installed
-      # Also with older util-linux these dependencies must be fetched manually:
-      #    util-linux : PreDepends: libblkid1 (= 2.40.4-5) but 2.41-4 is to be installed
-      #                 PreDepends: libmount1 (= 2.40.4-5) but 2.41-4 is to be installed
-      #                 PreDepends: libsmartcols1 (= 2.40.4-5) but 2.41-4 is to be installed
-      #                 PreDepends: libuuid1 (= 2.40.4-5) but 2.41-4 is to be installed
       #
       # Thus, on these older distros, test upgrade only up until the Debian Sid
-      # March 2025 version:
-      if grep -q -E 'bullseye|buster|stretch' /etc/os-release
+      # March 2025 version (snapshot chosen just before coreutils/util-linux
+      # gained hard dependencies making upgrades from Bullseye/older impossible):
+      if grep -q -E 'bullseye|buster|stretch|jammy|focal' /etc/os-release
       then
         echo 'deb http://snapshot.debian.org/archive/debian/20250315T025205Z sid main' > /etc/apt/sources.list
       fi
@@ -246,6 +247,9 @@ build bullseye-backports:
   #   *************************************************************************
   # Therefore, an older base-files must be used:
   - |
+    # If apt install failed, it might be due to base-files needing usrmerge.
+    # Attempt workaround using base-files 13.2 (snapshot chosen just before
+    # base-files 13.3 started requiring usrmerge).
     if [ "$APT_STATUS" = "failed" ]
     then
       curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/b/base-files/base-files_13.2_amd64.deb
@@ -259,12 +263,15 @@ build bullseye-backports:
   #   libc6 : Breaks: base-files (< 13.3~) but 13.2 is to be installed
   # Therefore, older libc6 and it's dependency libc6-bin must be used:
   - |
+    # If base-files workaround failed, it might be due to libc6 breaking older
+    # base-files. Attempt workaround using libc6 2.38 (snapshot chosen just
+    # before libc6 2.39 started breaking base-files < 13.3).
     if [ "$BASE_FILES_STATUS" = "failed" ]
     then
       curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/g/glibc/libc6_2.38-11_amd64.deb
       curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/g/glibc/libc-bin_2.38-11_amd64.deb
       # Apt version in Jessie does not support 'apt install ./package.deb', use this only for Stretch or newer
-      apt-get install -q --yes --no-install-recommends ./libc*_amd64.deb || true
+      apt-get install -q --yes --no-install-recommends ./libc*_*.deb || true
       # Ensure upgrades past 2.38-11 are blocked to avoid failure on usrmerge issue
       apt-mark hold libc6 libc-bin
       apt-get install -q --yes --fix-broken apt
@@ -287,7 +294,7 @@ build bullseye-backports:
       cd - # Back to CI run directory
       find /lib/*/libcrypt.* -ls # Show that new libcrypt is there
       apt-mark unhold libc6 libc-bin
-      apt-get install -q --yes --fix-broken --no-install-recommends ./libc*_amd64.deb || true
+      apt-get install -q --yes --fix-broken --no-install-recommends ./libc*_*.deb || true
       # Ensure upgrades past 2.38-11 are blocked to avoid failure on usrmerge issue
       apt-mark hold libc6 libc-bin
       apt-get install -q --yes apt
@@ -310,38 +317,42 @@ build bullseye-backports:
     # Note! If MariaDB is installed, this step will uninstall it.
     if dpkg -l login mount | grep -F '+deb9'
     then
-      apt-get remove login mount perl -qq --yes --allow-remove-essential || true
-      # Extra fix needed so MariaDB 10.1 shutdown in Stretch will proceed
-      test -L /lib || cp -av /usr/lib/lsb /lib/
-      apt-get remove login mount perl -qq --yes --allow-remove-essential || true
+      apt-get remove login mount -qq --yes --allow-remove-essential || true
+    fi
+  # Upgrades from Ubuntu Noble fail on:
+  #   Prevent: dpkg-divert: error:
+  #   'diversion of /lib32 to /.lib32.usr-is-merged by base-files' clashes
+  #    with 'diversion of /lib32 to /lib32.usr-is-merged by base-files'
+  # This is because Noble already has these:
+  #   $ dpkg-divert --list | grep 'by base-files'
+  #   diversion of /libx32 to /.libx32.usr-is-merged by base-files
+  #   diversion of /lib32 to /.lib32.usr-is-merged by base-files
+  #   diversion of /libo32 to /.libo32.usr-is-merged by base-files
+  # Circumvent them by simply removing them before starting upgrade, as the
+  # upgrade of base-files will immediately put them back again:
   - |
-    # Upgrades from Ubuntu Noble fail on:
-    #   Prevent: dpkg-divert: error:
-    #   'diversion of /lib32 to /.lib32.usr-is-merged by base-files' clashes
-    #    with 'diversion of /lib32 to /lib32.usr-is-merged by base-files'
-    # This is because Noble already has these:
-    #   $ dpkg-divert --list | grep 'by base-files'
-    #   diversion of /libx32 to /.libx32.usr-is-merged by base-files
-    #   diversion of /lib32 to /.lib32.usr-is-merged by base-files
-    #   diversion of /libo32 to /.libo32.usr-is-merged by base-files
-    # Circumvent them by simply removing them before starting upgrade, as the
-    # upgrade of base-files will immediately put them back again:
     if grep -q -E 'noble' /etc/os-release
     then
       BASE_DIVERSIONS="$(dpkg-divert --list | grep 'by base-files' | \
                        grep --only-matching --perl-regex 'of\K /[a-z0-9]+ ')"
       for x in $BASE_DIVERSIONS; do dpkg-divert --no-rename --remove $x; done
     fi
+  # Due to usrmerge, several upgrade attempts are needed until it passes,
+  # with some manual copying of files from /usr/bin/ to /bin/
+  # First 'apt-get upgrade' run likely fails on:
+  #   dpkg (subprocess): unable to execute installed bash package
+  #   post-installation script (/var/lib/dpkg/info/bash.postinst): No such file
+  #   or directory
+  # Second run fails on:
+  #   dpkg (subprocess): unable to execute installed dash package
+  #   post-installation script (/var/lib/dpkg/info/dash.postinst): No such file
+  #   or directory
+  # Third run fails on:
+  #   update-alternatives: error: alternative path /bin/more doesn't exist
+  # Fourth run likely passes.
   - |
-    # First 'apt-get upgrade' run fails on:
-    #   dpkg (subprocess): unable to execute installed bash package post-installation script (/var/lib/dpkg/info/bash.postinst): No such file or directory
-    # Second run fails on:
-    #   dpkg (subprocess): unable to execute installed dash package post-installation script (/var/lib/dpkg/info/dash.postinst): No such file or directory
-    # Third run fails on:
-    #   update-alternatives: error: alternative path /bin/more doesn't exist
-    # Repeat upgrade attempts until passes
     function usrmerge-temp-fix {
-      for x in bash dash sh more cp ln sleep
+      for x in bash cat cp dash ln more sh sleep
       do
         if [ -x /usr/bin/$x ]
         then
@@ -361,15 +372,14 @@ build bullseye-backports:
         exit 1
       fi
     done
-
-# The official Stretch repository has been archived
-.test-enable-stretch-archive-repos: &test-enable-stretch-archive-repos |
-  cat > /etc/apt/sources.list <<EOF
-  deb http://archive.debian.org/debian stretch main
-  deb http://archive.debian.org/debian-security stretch/updates main
-  EOF
+  # Extra fix needed to avoid running into:
+  #   Setting up rsync (3.3.0-1) ...
+  #   /etc/init.d/rsync: 31: .: cannot open /lib/lsb/init-functions: No such file
+  #   invoke-rc.d: initscript rsync, action "restart" failed.
+  - test -L /lib || cp -av /usr/lib/lsb /lib/
 
 .test-enable-artifacts-repo: &test-enable-artifacts-repo |
+  # List files so it can be verified from logs that correct artifacts are present
   find -ls -maxdepth 3
   apt-get install -qq --yes apt-utils
   apt-ftparchive packages . > Packages
@@ -442,11 +452,6 @@ build bullseye-backports:
     - command -v mysql && mysql --table -e "SHOW PLUGINS" | grep wsrep
     - command -v mariadb && mariadb --table -e "SHOW PLUGINS" | grep wsrep
     - *test-enable-sid-repos
-    # Extra fix needed to avoid running into:
-    #   Setting up rsync (3.3.0-1) ...
-    #   /etc/init.d/rsync: 31: .: cannot open /lib/lsb/init-functions: No such file
-    #   invoke-rc.d: initscript rsync, action "restart" failed.
-    - test -L /lib || cp -av /usr/lib/lsb /lib/
     - *test-enable-artifacts-repo
     # Start with regular upgrade (mysql-common and mariadb-common upgrade)
     # Avoid `-qq` in simulate, as on errors it would not show any context info
