Salsa CI: Prevent infinite loop in apt-get re-runs
If the upgrade to Debian unstable was permanently broken, the loop that
tried to reinstall known usrmerge dependent packages would run until
the whole test timed out in 1h.

Insert a counter to limit attempts.

diff --git a/debian/salsa-ci.yml b/debian/salsa-ci.yml
--- a/debian/salsa-ci.yml
+++ b/debian/salsa-ci.yml
@@ -278,10 +278,17 @@ test-crossbuild-armel:
         fi
       done
     }
+    ATTEMPT=0
     until apt-get install -q --yes bash dash util-linux coreutils lsb-base login mount
     do
       test -f /bin/cp || /usr/bin/cp -av /usr/bin/cp /bin/
       usrmerge-temp-fix || true
+      ATTEMPT=$((ATTEMPT + 1))
+      if [ $ATTEMPT -ge 10 ]
+      then
+        echo "ERROR: Unable to apply usrmerge upgrade workaround"
+        exit 1
+      fi
     done
 
 # The official Stretch repository has been archived
